/**
 * Business Central API Client
 * 
 * Connects to BC SaaS via OAuth2 (Client Credentials flow)
 * Uses BC API v2.0 (Microsoft recommended)
 * 
 * API Base: https://api.businesscentral.dynamics.com/v2.0/{tenant}/{env}/api/v2.0
 */

const https = require('https');

class BCClient {
  constructor(config) {
    this.tenantId = config.tenantId;
    this.clientId = config.clientId;
    this.clientSecret = config.clientSecret;
    this.environment = config.environment || 'sandbox';
    this.companyName = config.companyName;
    this.companyId = null;
    this.accessToken = null;
    this.tokenExpiry = 0;
  }

  // ─── OAuth2 Token ────────────────────────────────────────────
  async getToken() {
    if (this.accessToken && Date.now() < this.tokenExpiry) {
      return this.accessToken;
    }

    const tokenUrl = `https://login.microsoftonline.com/${this.tenantId}/oauth2/v2.0/token`;
    
    const body = new URLSearchParams({
      grant_type: 'client_credentials',
      client_id: this.clientId,
      client_secret: this.clientSecret,
      scope: 'https://api.businesscentral.dynamics.com/.default',
    }).toString();

    const response = await this._httpsRequest(tokenUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body,
    });

    const data = JSON.parse(response);
    this.accessToken = data.access_token;
    this.tokenExpiry = Date.now() + (data.expires_in - 60) * 1000; // Refresh 1 min early
    
    return this.accessToken;
  }

  // ─── API Base URL ────────────────────────────────────────────
  get apiBase() {
    return `https://api.businesscentral.dynamics.com/v2.0/${this.tenantId}/${this.environment}/api/v2.0`;
  }

  // ─── Initialize (find company ID) ───────────────────────────
  async init() {
    const token = await this.getToken();
    const companies = await this._apiGet('/companies');
    
    const company = companies.value.find(c => 
      c.name.toUpperCase().includes(this.companyName.toUpperCase()) ||
      c.displayName.toUpperCase().includes(this.companyName.toUpperCase())
    );

    if (!company) {
      const available = companies.value.map(c => c.name).join(', ');
      throw new Error(`Company "${this.companyName}" not found. Available: ${available}`);
    }

    this.companyId = company.id;
    console.log(`  ✅ Connected to BC: ${company.displayName} (${company.id})`);
    return company;
  }

  // ─── Items (Item Cards) ─────────────────────────────────────
  
  /**
   * Get all items from BC (paginated)
   */
  async getItems(filter = '', top = 1000) {
    let url = `/companies(${this.companyId})/items?$top=${top}`;
    if (filter) url += `&$filter=${encodeURIComponent(filter)}`;
    
    const allItems = [];
    let nextLink = url;
    
    while (nextLink) {
      const response = await this._apiGet(nextLink);
      allItems.push(...(response.value || []));
      
      // Handle pagination
      if (response['@odata.nextLink']) {
        nextLink = response['@odata.nextLink'].replace(this.apiBase, '');
      } else {
        nextLink = null;
      }
    }
    
    return allItems;
  }

  /**
   * Search items by number or description
   */
  async searchItems(searchTerm) {
    const filter = `contains(number,'${searchTerm}') or contains(displayName,'${searchTerm}')`;
    return this.getItems(filter, 50);
  }

  /**
   * Create a new blank Item Card
   */
  async createItem(itemData) {
    const payload = {
      // number is auto-generated by BC number series
      displayName: itemData.description || itemData.displayName || 'NEW ITEM',
      type: itemData.type || 'Inventory',   // Inventory, Service, Non-Inventory
      unitOfMeasureCode: itemData.uom || 'EA',
      gtin: itemData.part_number || '',
    };

    const result = await this._apiPost(`/companies(${this.companyId})/items`, payload);
    return result;
  }

  // ─── Sales Quotes ───────────────────────────────────────────
  
  /**
   * Create a Sales Quote header
   */
  async createSalesQuote(quoteData) {
    const payload = {
      customerNumber: quoteData.customerNumber,
      externalDocumentNumber: quoteData.externalDocNumber || '',
      // documentDate: quoteData.date || new Date().toISOString().split('T')[0],
    };

    const result = await this._apiPost(`/companies(${this.companyId})/salesQuotes`, payload);
    return result;
  }

  /**
   * Add a line to a Sales Quote
   */
  async addSalesQuoteLine(quoteId, lineData) {
    const payload = {
      lineType: lineData.type || 'Item',
      itemId: lineData.itemId,
      quantity: lineData.quantity || 1,
      unitOfMeasureCode: lineData.uom || 'EA',
      description: lineData.description || '',
    };

    const result = await this._apiPost(
      `/companies(${this.companyId})/salesQuotes(${quoteId})/salesQuoteLines`,
      payload
    );
    return result;
  }

  /**
   * Get existing Sales Quotes
   */
  async getSalesQuotes(filter = '', top = 50) {
    let url = `/companies(${this.companyId})/salesQuotes?$top=${top}`;
    if (filter) url += `&$filter=${encodeURIComponent(filter)}`;
    return this._apiGet(url);
  }

  // ─── HTTP Helpers ────────────────────────────────────────────
  
  async _apiGet(urlPath) {
    const token = await this.getToken();
    const fullUrl = urlPath.startsWith('http') ? urlPath : `${this.apiBase}${urlPath}`;
    
    return JSON.parse(await this._httpsRequest(fullUrl, {
      method: 'GET',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/json',
      },
    }));
  }

  async _apiPost(urlPath, data) {
    const token = await this.getToken();
    const body = JSON.stringify(data);
    
    return JSON.parse(await this._httpsRequest(`${this.apiBase}${urlPath}`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
      body,
    }));
  }

  async _apiPatch(urlPath, data, etag) {
    const token = await this.getToken();
    const body = JSON.stringify(data);
    
    const headers = {
      'Authorization': `Bearer ${token}`,
      'Content-Type': 'application/json',
      'Accept': 'application/json',
    };
    if (etag) headers['If-Match'] = etag;
    
    return JSON.parse(await this._httpsRequest(`${this.apiBase}${urlPath}`, {
      method: 'PATCH',
      headers,
      body,
    }));
  }

  _httpsRequest(url, options) {
    return new Promise((resolve, reject) => {
      const urlObj = new URL(url);
      
      const reqOptions = {
        hostname: urlObj.hostname,
        port: 443,
        path: urlObj.pathname + urlObj.search,
        method: options.method || 'GET',
        headers: options.headers || {},
        timeout: 30000,
      };

      const req = https.request(reqOptions, (res) => {
        let data = '';
        res.on('data', chunk => data += chunk);
        res.on('end', () => {
          if (res.statusCode >= 400) {
            reject(new Error(`BC API ${res.statusCode}: ${data.substring(0, 500)}`));
          } else {
            resolve(data);
          }
        });
      });

      req.on('error', reject);
      req.on('timeout', () => { req.destroy(); reject(new Error('Request timeout')); });

      if (options.body) req.write(options.body);
      req.end();
    });
  }
}

module.exports = { BCClient };
